class ApplicationController < ActionController::Base
    
    #generated by Devise gem - creates, updates and deletes users (names, emails, passwords) in Users table. 
    #Devise manages all authentication in Plantr (ensuring a user is logged in/verified to access functions like listings and purchasing.)
    #Look to documantation to customise:
    #https://github.com/heartcombo/devise
     before_action :authenticate_user!

    protect_from_forgery with: :exception

     before_action :configure_permitted_parameters, if: :devise_controller?

     protected

          def configure_permitted_parameters
               devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password)}

               devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password)}
          end

end
